create table daily_report_http (
"ts" TIMESTAMP NOT NULL,
"uid" varchar(20),
"orig_h" varbinary(50),
"orig_p" integer NOT NULL,
"resp_h" varbinary(50),
"resp_p" integer NOT NULL,
"trans_depth" integer NOT NULL,
"method" varchar(10),
"host" varchar(100),
"uri" varchar(500),
"referrer" varchar(100),
"version" varchar(100),
"user_agent" varchar(100),
"req_body_len" integer,
"resp_body_len" integer,
"status_code" integer,
"status_msg" varchar(50),
"info_code" integer,
"info_msg" varchar(100),
"tags" varchar(500),
"username" varchar(50),
"password" varchar(50),
"proxied" varchar(500),
"orig_fuids" varchar(500),
"orig_filenames" varchar (500),
"orig_mime_types" varchar (500),
"resp_fuids" varchar(500),
"resp_filenames" varchar (500),
"resp_mime_types" varchar (500)
)
PARTITION BY EXTRACT(hour FROM ts);