create table daily_report_smtp (
"ts" TIMESTAMP NOT NULL,
"uid" varchar(20),
"orig_h" varbinary(50),
"orig_p" integer NOT NULL,
"resp_h" varbinary(50),
"resp_p" integer NOT NULL,
"trans_depth" integer NOT NULL,
"helo" varchar(500),
"mail_from" varchar(100),
"rcpt_to" varchar(100),
"date" varchar(100),
"from_email" varchar(100),
"to_email" varchar(100),
"cc" varchar(100),
"reply_to" varchar(100),
"msg_id" varchar(100),
"in_reply_to" varchar(500),
"subject" varchar(100),
"x_originating_ip" varbinary(50),
"first_received" varchar(500),
"second_received" varchar(500),
"last_reply" varchar(500),
"path" varchar(500),
"user_agent" varchar(100),
"tls" varchar(1),
"process_recived_from" varchar(1),
"has_client_activity" varchar(1)
)
PARTITION BY EXTRACT(hour FROM ts);
