CREATE TABLE targetresult (
"time" TIMESTAMP NOT NULL,
"OOO_SibirInvest" INTEGER,
"MAJESTIC_HOSTING_01" INTEGER,
"SIA_IT_Services" INTEGER,
"_45_136_111_0" INTEGER,
"RETHEMHOSTING" INTEGER,
"RM_Engineering_LLC" INTEGER,
"IP_Volume_inc" INTEGER,
"PE_Ivanov_Vitaliy_Sergeevich" INTEGER,
"OOO_Network_of_data_centers_Selectel" INTEGER,
"JSC_The_First" INTEGER,
"Romanenko_Stanislav_Sergeevich" INTEGER,
"KINX" INTEGER,
"VNPT_Corp" INTEGER,
"_45_136_108_0" INTEGER,
"Dm_Auto_Eood" INTEGER,
"RN_Data_SIA" INTEGER,
"ABC_Consultancy" INTEGER,
"CT_HangZhou_IDC" INTEGER,
"TimeWeb_Ltd_" INTEGER,
"_185_175_93_0" INTEGER,
"Veles_LLC" INTEGER,
"Zomro_B_V_" INTEGER,
"OVH_SAS" INTEGER )